FS 1409 update application question forms
communitiesuk/funding-service-design-frontend pull request #128
Opened 2022-09-13 16:11 UTC by ramsharma-prog

Application questions update as per the new prototype

2022-09-13 19:37 UTC, harryyo approved these changes
👍

2022-09-14 13:06 UTC, adamdavies1 requested changes

2022-09-14 13:11 UTC, ramsharma-prog commented on form_jsons/public/community-engagement.json
> +      "next": [{ "path": "/check-your-answers" }]
Okay will amend it manually & add back link as well when finished updating other contents

2022-09-14 16:08 UTC, ramsharma-prog commented on form_jsons/public/community-engagement.json
> +      "next": [{ "path": "/check-your-answers" }]
Done!

2022-09-20 09:37 UTC, adamdavies1 approved these changes
LGTM

2022-09-20 09:37 UTC, merged