FS3530: Update eligibility button action
communitiesuk/funding-service-design-frontend pull request #594
Opened 2024-05-20 12:30 UTC by NarenderRajuB

Add eligibility button action

2024-06-04 13:19 UTC, srh-sloan reviewed
Couple of comments, again nothing major

2024-06-04 13:22 UTC, NarenderRajuB commented on app/helpers.py
> +    formatted_data["metadata"]["fund_name"] = fund_name
We need this to pass to result page where we need this to pass to new application

2024-06-06 12:37 UTC, nuwan-samarasinghe requested changes

2024-06-06 12:37 UTC, nuwan-samarasinghe commented on app/default/eligibility_routes.py
> +    current_app.logger.info(f"Eligibility launch result: {fund_name} {round_name}")
Can we have some comments to express each methods functionality

2024-06-06 12:37 UTC, nuwan-samarasinghe commented on app/translations/cy/LC_MESSAGES/messages.po
> +msgid "%(fund_title)s "
Probably we might need to remove this or find a way to not to populate it here

2024-06-07 08:25 UTC, srh-sloan approved these changes

2024-06-07 08:37 UTC, nuwan-samarasinghe approved these changes

2024-06-07 09:12 UTC, merged