Fs 394 add performance testing
communitiesuk/funding-service-design-frontend pull request #8
Opened 2022-01-17 21:10 UTC by damien-cooke

This will always pass as it just runs the tests and produces a report. Need to add a feature for failing when a certain amount of requests fail.

2022-01-17 22:39 UTC, stevewalton28 requested changes

2022-01-17 22:39 UTC, stevewalton28 commented on .github/workflows/govcloud.yml
> +          retention-days: 5
New line at end of file needed

2022-01-17 22:58 UTC, stevewalton28 approved these changes

2022-01-18 09:09 UTC, endamccormack approved these changes

2022-01-18 09:31 UTC, merged